# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main  # Déclenchement automatique sur chaque push dans main

pool:
  vmImage: 'ubuntu-latest'  # Image de la machine d'agent

variables:
  imageName: pfe/backend  # Nom du repo Docker (ex: mon-utilisateur/backend)

steps:
- task: Docker@2
  displayName: 'Build and push Docker image to Docker Hub'
  inputs:
    containerRegistry: 'pfe-backend'  # Nom exact de la connexion Docker
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: 'pfe/backend/Dockerfile'
    tags: |
      latest
